### ISSUE TITLE
Use gRPC for sharding

### ISSUE THREAD

**Issue by edbaunton** [buildbarn/bb-storage#1]
As discussed at FOSDEM, we could research the use of gRPC for the sharding of the bb-storage. The overview [here](https://grpc.io/blog/loadbalancing) provides some methods, I believe the specific setup we considered was a service providing the mapping which would have been the "lookaside", although haproxy might be suitable too.

**Comment by EdSchouten** [comment]
Hi Ed! Nice to see you are already filing issues based on our discussions.

I gave this some more thought on the way back home the other day. I am not convinced that gRPC load balancing is going to help us a lot here. The article you linked says this:

> A large scale gRPC deployment typically has a number of identical back-end instances, and a number of clients.

In the case of bb-storage, the backends are only identical in terms of the protocol, but not in terms of functionality. Each of them represents its own shard; a fragment of the key space. The article doesn't seem to mention sharding at all. I'd suspect that if sharding was supported, you would still need to write code for your application to describe for every RPC which field(s) in the input message must be combined to obtain a shard identifier. I am not aware that anything like that can be specified.

Furthermore, it's also not just a matter of forwarding an RPC to exactly one shard. In the case of `FindMissingBlobs()` we must partition the digests and forward requests possibly to multiple shards. As the logic for partitioning and recombining strongly depends on your schema, I don't think gRPC would be able to automate a lot there. The current code for doing that is defined here:

https://github.com/buildbarn/bb-storage/blob/dfb8c06f0dda1d945284616c75ed4b3706906b8b/pkg/blobstore/sharding/sharding_blob_access.go#L69-L97

What are your thoughts on this?

**Comment by edbaunton** [comment]
Yes, you are totally correct!

I guess the context in which this came up was a little vague - I just opened the ticket so we wouldn't forget to investigate.

I believe we were discussing the way sharding works when a node fails and we visited the idea of implementing a service that would provide the shard mappings (taking into account crashes etc.); @buchgr then mentioned that gRPC has support for this natively. So this is to check in on that.

More specifically, I think he was referring to the [grpclb](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md#architecture) policy. This basically defers the resolution of the endpoint via the loader-balancer. Since, as you say, the routing is not simple and requires introspection of the requests themselves, you would likely have to implement a custom policy in one of the existing LB implementations - as well as the client. I am not familiar with the setup and the documentation seems a little light. It might be the case that this lookaside loadbalancing is for fixing clients to a particular subset of servers rather than sharding, as you said.

**Comment by EdSchouten** [comment]
Hi Ed,

> I believe we were discussing the way sharding works when a node fails and we visited the idea of implementing a service that would provide the shard mappings (taking into account crashes etc.)

Exactly. One solution would be to have a `DynamicBlobAccess` that calls into a streaming RPC in the background. Over that streaming RPC it receives `BlobAccessConfiguration` messages. Such an approach would make it possible to use sharding with health checking for any storage backend (Redis, S3); not just gRPC.

**Comment by mickael-carl** [comment]
Looking at this, it doesn't look like doing sharding with gRPC is the right way to go. Instead we should simply use the sharding blob access.
