### ISSUE TITLE
Bazel InvocationID is not forwarded to bb-scheduler

### ISSUE THREAD

**Issue by stefanhoelzl** [buildbarn/bb-storage#108]
When a `remoteexecution.Execute`grpc call is [forwarded](https://github.com/buildbarn/bb-storage/blob/master/pkg/builder/forwarding_build_queue.go#L50) to the bb-scheduler the bazel invocation id gets lost.

The scheduler then creates only a single queue for all bazel invocations.

**Comment by EdSchouten** [comment]
Hey there!
Just make sure you add the following to the gRPC client configuration of your frontend containers:
```
forwardMetadata: ['build.bazel.remote.execution.v2.requestmetadata-bin']
```
That ensures that the metadata that Bazel sends is forwarded to the scheduler.
