### ISSUE TITLE
Missing shell in bb-storage docker image

### ISSUE THREAD

**Issue by ferraith** [buildbarn/bb-storage#153]
From your statement https://github.com/buildbarn/bb-storage/issues/27 I would expect that a shell e.g. `sh` is baked into the docker image published to Docker Hub. Because `kubectl exec ...` is failing for me I extracted the image, but couldn't find any shell.

I assume this is because `go_image` is called:
https://github.com/buildbarn/bb-storage/blob/81407c8ba4eadaf53e13c21af5203007c38ceba6/cmd/bb_storage/BUILD.bazel#L40

From my understanding the pure flag ensure that an app-only image is built.

**Comment by EdSchouten** [comment]
Closing this, as @ferraith found a way to debug without putting a shell in the container.
