### ISSUE TITLE
Panic in local blockstore write

### ISSUE THREAD

**Issue by joeljeske** [buildbarn/bb-storage#159]
Within bb_worker, I sometimes experience a panic when writing to the local blockstore.

`bb-storage@6bd6d5d`

```
panic: runtime error: slice bounds out of range [:-53506]
goroutine 170339 [running]:
github.com/buildbarn/bb-storage/pkg/blobstore/local.(*blockDeviceBackedBlockWriter).Write(0xc001ca96c0, {0xc002860000?, 0x10000, 0x10000?})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/local/block_device_backed_block_allocator.go:339 +0x745
github.com/buildbarn/bb-storage/pkg/blobstore/buffer.intoWriterViaChunkReader({0x14b7998?, 0xc001ca9700}, {0x14ab820, 0xc001ca96c0})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/buffer/common_conversions.go:24 +0x135
github.com/buildbarn/bb-storage/pkg/blobstore/buffer.(*casClonedBuffer).IntoWriter(0xc00231b650?, {0x14ab820, 0xc001ca96c0})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/buffer/cas_cloned_buffer.go:91 +0x3c
github.com/buildbarn/bb-storage/pkg/blobstore/local.(*blockDeviceBackedBlock).Put.func1({0x14ca098?, 0xc0001ce850?})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/local/block_device_backed_block_allocator.go:255 +0x4d
github.com/buildbarn/bb-storage/pkg/blobstore/local.(*OldCurrentNewLocationBlobMap).Put.func1({0x14ca098?, 0xc0001ce850?})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/local/old_current_new_location_blob_map.go:374 +0x47
github.com/buildbarn/bb-storage/pkg/blobstore/local.(*flatBlobAccess).Put(0xc0007b1100, {0x411823d000000000?, 0xc002623fa8?}, {{0xc000cd0f50?, 0x0?}}, {0x14ca098, 0xc0001ce850})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/local/flat_blob_access.go:294 +0x11c
github.com/buildbarn/bb-storage/pkg/blobstore.(*metricsBlobAccess).Put(0xc0003e13f0, {0x14bbe18, 0xc000bc1f20}, {{0xc000cd0f50?, 0x0?}}, {0x14ca098?, 0xc0001ce850?})
	external/com_github_buildbarn_bb_storage/pkg/blobstore/metrics_blob_access.go:140 +0x132
github.com/buildbarn/bb-storage/pkg/blobstore/replication.(*localBlobReplicator).ReplicateSingle.func1()	external/com_github_buildbarn_bb_storage/pkg/blobstore/replication/local_blob_replicator.go:38 +0x3e
github.com/buildbarn/bb-storage/pkg/blobstore/buffer.newCASBufferWithBackgroundTask.func1()
	external/com_github_buildbarn_bb_storage/pkg/blobstore/buffer/cas_buffer_with_background_task.go:42 +0x26
created by github.com/buildbarn/bb-storage/pkg/blobstore/buffer.newCASBufferWithBackgroundTask
	external/com_github_buildbarn_bb_storage/pkg/blobstore/buffer/cas_buffer_with_background_task.go:41 +0x1aa
```

I cannot yet reliably reproduce this, but it is guessed that this occurs when the syscall pwrite returns no-error but does a short-write, so `return n < len(p)`, but `err == nil`

```go
func (bd *memoryMappedBlockDevice) WriteAt(p []byte, off int64) (int, error) {
        // Let write actions go through the file descriptor. Doing so
        // yields better performance, as writes through a memory map
        // would trigger a page fault that causes data to be read.
        //
        // TODO: Maybe it makes sense to let unaligned writes that would
        // trigger reads anyway to go through the memory map?
        return unix.Pwrite(bd.fd, p, off)
}
```

Then, io.WriterAt requires that if `n < len(p)`  that `err != nil`

This potentially could be solved by adding a loop to memoryMappedBlockDevice.WriteAt(), to repeatedly call it in case we see short writes.

**Comment by joeljeske** [comment]
After further investigation, this panic was caused by lack of space on disk. If there is proper disk space available, I do not see these panics. Presumably bb-worker is allowed to panic unexpectedly if it does not have proper space available. Closing this ticket.

(In my specific case, disk space was being lost due to a buggy shiftfs kernel extension, bb-worker was correctly using the amount of space it was directed to use, however, the space could not be written to.)

**Comment by EdSchouten** [comment]
bb_worker should not have crashed like that. Reopening.

**Comment by EdSchouten** [comment]
Hi Joel,
I just merged a change that should cause bb_storage to return proper "No space left on device" errors, instead of crashing. Please give it a try!

**Comment by NVGreg** [comment]
While reviewing the fix from `0c1aff39`, I noticed two edge cases in the current loop:

- `unix.Pwrite` may return an error with a negative raw count, so `err` should be checked before adding `n` to the total.
- A zero-progress `(0, nil)` result would leave the loop spinning.

Would you accept a small PR that checks `err` first and returns `io.ErrShortWrite` when `n <= 0`, with a regression test for the error-count case?

**Comment by EdSchouten** [comment]
Hey @NVGreg ,

> unix.Pwrite may return an error with a negative raw count, so err should be checked before adding n to the total.

I just looked at the implementation of `unix.Pwrite()`, and you are correct: it may return `-1` in case of an error. Interesting!

> A zero-progress (0, nil) result would leave the loop spinning.

My question is, under which conditions would this actually happen? I can imagine it only occurs if you call `unix.Pwrite()` with a zero-length input buffer, which we never do.

**Comment by EdSchouten** [comment]
I've just sent out #355 to fix the issue of the write length being potentially negative. With regards to (0, nil), I just found this StackOverflow post that confirms my suspicion: this shouldn't happen. Though feel free to correct me!

https://stackoverflow.com/questions/41904221/can-write2-return-0-bytes-written-and-what-to-do-if-it-does
