### ISSUE TITLE
Configuration files don't permit comments (JSON)

### ISSUE THREAD

**Issue by ailiev** [buildbarn/bb-storage#16]
I think it's a very useful option to have. AFAICS the jsonpb library doesn't have an option to accept comments in the JSON.

**Comment by mickael-carl** [comment]
Correct, and that is one drawback of switching to jsonpb. However, while mentioning it in #17, jsonnet also supports adding comments to jsonnet files, which will be stripped away when generating the end configuration.

**Comment by mickael-carl** [comment]
@ailiev this is now supported out of the box since a56d3a1: you can feed bb-storage (and all other components of Buildbarn) Jsonnet files and it will render them for you, allowing you to put comments in the configuration files.
