### ISSUE TITLE
Doc Update: ISCC / AC storages are only compatible with local replicator

### ISSUE THREAD

**Issue by joeljeske** [buildbarn/bb-storage#161]
It appears that all replicator types, other than the `local` replicator, are incompatible with the ISCC and AC data storage. The deduplication  / concurrencyLimiting  replicators rely on use of FindMissingBlobs and thus fail at runtime when attempted to be used. 

Related, it would be nice if the proto config guarded against use of incorrect decorators like these.

**Comment by EdSchouten** [comment]
I think concurrencyLimiting should be fine, right? That one only places a semaphore around calls. But you're right about the deduplicating. That one should be specific to CAS and ICAS, as it depends on FindMissing(). Will fix!
