### ISSUE TITLE
Publish images with arm64

### ISSUE THREAD

**Issue by alexeagle** [buildbarn/bb-storage#198]
Today, the bb-storage container image is published for x86_64 only.

```
% docker image inspect --format "{{.ID}} {{.Architecture}}" ghcr.io/buildbarn/bb-storage:20240311T070255Z-7b232a7
sha256:e1dcf8ca0b7b17a825ae8853aeb9db555b879302b851193592b239381eb32098 amd64
```

However there are some great instance types like https://instances.vantage.sh/aws/ec2/is4gen.medium which provide double the NVME per instance and 2.5X the I/O bandwidth and $0.144/hr vs $0.172 for `i4i.large`

These instances need arm64 architecture.
Note, I'm happy to work on a PR for this.

**Comment by alexeagle** [comment]
Note, I suggest we also move away from https://github.com/bazelbuild/rules_docker at the same time, it's been long-unmaintained and now archived. rules_oci makes publishing multi-arch images easy, we even have some examples on-hand doing so for Go binaries.

**Comment by alexeagle** [comment]
Nice, now of course my next task is to wait on a release, do you have a regular cadence for them, or does it help to request one?

**Comment by EdSchouten** [comment]
Every commit is a release.

**Comment by alexeagle** [comment]
Got it, I noticed it was red, sent you #202
