### ISSUE TITLE
How we do shell access to any pods?

### ISSUE THREAD

**Issue by boseabhishek** [buildbarn/bb-storage#27]
We have recently started exploring Buildbarn. Sorry for silly questions but can we do shell access to the pods for an insight of especially the storage (what's the data in CAS/AC in case of a circular storage?). I get the fact that logging is only enabled for failure as per best practices and to avoid unnecessary logging.. Thanks

**Comment by EdSchouten** [comment]
All of our container images, except bb-worker, use `go_image()` nowadays. This means that all containers now have a usable shell environment. `kubectl exec` should work properly now. Enjoy!
