### ISSUE TITLE
Add support for BatchUpdateBlobs

### ISSUE THREAD

**Issue by jeremiahbonney** [buildbarn/bb-storage#3]
When trying to do a simple test of `recc + buildgrid + bb-storage`, all uploads fail due to `recc` making use of the BatchUpdateBlobs endpoint for collections of blobs under a certain size. There doesn't seem to be a way specified in the API to tell clients to use `bytestream.Write` only<sup>[1]</sup>, so it would be great if it was supported. 

[1] I suppose the Capabilities API could report a very small non-zero number for `max_batch_total_size_bytes`, but having support for BatchUpdateBlobs would be better IMO.

**Comment by EdSchouten** [comment]
Hi there! Could you give the `batch-update-blobs` branch a try? Thanks!

**Comment by jeremiahbonney** [comment]
Gave it a try and it worked like a charm! `recc` was able to upload blobs no problem with the new branch.

**Comment by EdSchouten** [comment]
Thanks for testing!
