### ISSUE TITLE
S3 incorrect bucket name isn't reported

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-storage#31]
Whilst configuring my bb-storage to use the S3 cloud blob storage I noticed that I was getting `io.grpc.StatusRuntimeException: UNKNOWN: EOF` in Bazel without any error reporting from Buildbarn.

This turned out to be because I had set my `bucket` parameter incorrectly inside of the s3 configuration.

The storage instance should produce some form of log to report this, which may or may not be propagated to Bazel. The likely source of this issue is at [cloud_blob_access.go#L33](https://github.com/buildbarn/bb-storage/blob/master/pkg/blobstore/cloud_blob_access.go#L33) and likely resides within the other functions within this file. This get should definitely be reporting some form of issue, but perhaps gocloud.dev isn't providing any sort of error?

The code at [create_blob_access.go#L193](https://github.com/buildbarn/bb-storage/blob/d161538a1d3c6ac8c49f0bb1c373fbb389007703/pkg/blobstore/configuration/create_blob_access.go#L193) suggests that when provided with this incorrect configuration, `gocloud.dev` isn't returning an `err` value.

**Comment by cphang99** [comment]
This sounds like an issue in gocloud rather than buildbarn code. Is there any validation that the bucket name is valid, or is it just establishing a session?

https://github.com/google/go-cloud/blob/master/blob/s3blob/s3blob.go#L159

**Comment by EdSchouten** [comment]
I agree with Chris on this. This would better be fixed in go-cloud.
