### ISSUE TITLE
Call gazelle instead of buildifier in CI pipeline

### ISSUE THREAD

**Issue by cphang99** [buildbarn/bb-storage#42]
Also see: https://github.com/buildbarn/bb-remote-execution/issues/37

To reduce duplication, we could also consider breaking this all out into a parent set of actions that the bb-* repositories can call upon. This would probably be a new repository in the buildbarn namespace.

**Comment by EdSchouten** [comment]
Fixed in https://github.com/buildbarn/bb-storage/commit/aea4f61a3dac9aa4d454cc0f99983fe8afac29f5
