### ISSUE TITLE
pkg/grpc: Add an Authenticator for OAuth2/OIDC/JWTs

### ISSUE THREAD

**Issue by EdSchouten** [buildbarn/bb-storage#48]
Buildbarn's story with regards to authentication is becoming a lot more complete:

- Bazel added proper support for passing in `Authentication: Bearer ${foo}` headers in https://github.com/bazelbuild/bazel/pull/10015  and https://github.com/bazelbuild/bazel/pull/10634.
- Buildbarn nowadays has a decent authentication layer in [pkg/grpc](https://github.com/buildbarn/bb-storage/tree/master/pkg/grpc).
- https://github.com/buildbarn/bb-storage/commit/4f5fdb65fbf998e154ffd74119a2cda68354213e added support for credential forwarding from gRPC servers to gRPC clients.

All we need to do now is add a proper implementation of Authenticator in pkg/grpc that uses OAuth2, OIDC, or just plain JWTs. What ever is the big trend nowadays. Maybe some of the code in #6 may be repurposed.

**Comment by mickael-carl** [comment]
I believe this is partially solved by #65 ?

**Comment by EdSchouten** [comment]
Yep! I think we still need an OAuth2 implementation of Authenticator, so that a gRPC server can allow/deny access.

**Comment by EdSchouten** [comment]
JWT authentication has been added. Further TODOs are to improve flexibility in areas of enforcing that certain claims are set, or to carry information on claims into the authorization framework. All these kinds of things can be implemented outside of this issue.

Furthermore, this is only adding JWT support; not OAuth2 or OIDC. Let's tackle that later on.
