### ISSUE TITLE
Add implicit zero-sized CAS blob

### ISSUE THREAD

**Issue by moroten** [buildbarn/bb-storage#56]
During the monthly https://github.com/bazelbuild/remote-apis meeting 2020-04-14, the following was decided:
> We should standardize this. Servers should allow references to the empty blobs, and should support serving the empty blob even if it has not been uploaded. Clients should feel free to optimize within this to avoid uploading or downloading empty blobs.

Implementing this will sort out the Bazel behaviour mentioned in https://github.com/bazelbuild/bazel/issues/11063.

**Comment by EdSchouten** [comment]
It's a pity we didn't use the occasion to simply say: digests with size zero are not allowed to exist. It's either a nil digest, or a digest with a size > 0. That would have solved this problem in a far more natural and less ambiguous way. But I guess we're simply getting to the point that we all have to be bug for bug compatible with Bazel. Great.

**Comment by mostynb** [comment]
> It's a pity we didn't use the occasion to simply say: digests with size zero are not allowed to exist. It's either a nil digest, or a digest with a size > 0.

I had the same thought when implementing this for bazel-remote. Something to suggest for REAPIv3?
