### ISSUE TITLE
Dealing with eventual consistency issues

### ISSUE THREAD

**Issue by allada** [buildbarn/bb-storage#57]
We have a setup that looks something like:
```
Is less than 4mb:
  -> Use Redis
Else:
  -> Use S3
```

We are also using remote execution nodes. We are trying to keep our points of failure low, so our CAS servers only serve clients and our workers directly talk to S3 and redis. This allows us to scale every easily with minimal points of failure.

We are also trying to get our clients setup (in bazel) with `--remote_download_toplevel` and `--remote_download_minimal`, however we have found that S3 is caching our 404 (cache misses). This is especially problematic for us because in what is happening is:
```
Client -> CAS -> S3     -> Do you have ObjectA?
S3     -> CAS -> Client -> No (404)
Client -> Worker        -> Go build ObjectA
Worker -> S3            -> Put ObjectA
Worker -> Client        -> Done (client does not download ObjectA)
Client -> Worker        -> Go build ObjectB that uses ObjectA
Worker -> S3            -> Do you have ObjectA?
S3     -> Worker        -> No (404) (cached result).
Worker -> Client        -> Give me ObjectA
Client -> .... Failure because it expected ObjectA to exist.
```

I would really prefer not to put another point of failure between S3 and the workers/cas instances. The CAS instances are really light weight in our setup and only used to forward data from S3 and redis, but not cache stuff locally (yet). If put a CAS node in front of S3 we'll add a point of failure + the maintenance of them, plus we'd have to figure out a way to synchronize their consistency.

What I think would be the best solution is to extend the way `ExistenceCachingBlobAccessConfiguration` works to have an additional optional `BlobAccessConfiguration` which can be used for the key lookup and the value lookups always go to `backend`. In our case we'd use redis as our existence database and S3 as our blob store. We'd also need to add a salt of some kind to prevent this "cache" entry from being a positive hit but no data associated with it when sharing the blobstore with the real data.

We are happy to implement this, but figured I'd query here before we go off and do it.

**Comment by EdSchouten** [comment]
Hey Nathan,
Quick question: have you seen [this document](https://github.com/buildbarn/bb-adrs/blob/master/0002-storage.md)? To summarise, what I suggest that people do to get decent performance and consistency is to build a RAID-10 setup of systems that use LocalBlobAccess. Be sure to give that a try!

**Comment by allada** [comment]
Awesome, that read was very useful. We have decided to revise our layout into:
* 2-3 large CAS instances with sharding to each other using local storage on Raid0 setup
  - (we may add a mirroring set in the future depending on reliability needs)
* Worker nodes will use the `read_caching` with `fast` set to S3 and `slow` set to the CAS instances
* Entry points will connect to one of the large CAS instances
* Workers will first try S3 and if fails to find it will download from one of the large CAS instances and upload it to S3

This should keep the bulk of the workload on S3 instead of the CAS. Granted all data must go through the CAS, but I think it's safe to assume most data will eventually be mirrored to S3 and since (from what I have read) S3 is limited to 25gbps per instance, we won't be suffering much on the worker nodes.

I think one thing that we may end up needing is the ability to verify the checksum of the S3 data and purge it if the checksum does not match. In early testing I have seen a couple cases of zero-byte data being downloaded from s3, but I have not yet dug deep into this issue.
