### ISSUE TITLE
Connect to GCS using Workload Identity in GKE.

### ISSUE THREAD

**Issue by GeniyX** [buildbarn/bb-storage#68]
An attempt to connect to the GCS bucket with enabled [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) fails with the following log:
```
ERROR: /gcp/namespaces/vpn/certs-generator/BUILD.bazel:4:1 Executing genrule //build/linters/metalinter_lib:generated-metalinter failed (Exit 34). Note: Remote connection/protocol failed with: execution failed io.grpc.StatusRuntimeException: UNKNOWN: blob (key "ace0c0360d8d2c139fbcb5abfcf437743c458f1065d152ecbdf7b72bcbb21a54c5-142-remote-execution") (code=Unknown):
 Get "https://storage.googleapis.com/bazel-remote-execution-trusted.project-id.organisation-name/ace0c0360d8d2c139fbcb5abfcf437743c458f1065d152ecbdf7b72bcbb21a54c5-142-remote-execution": metadata: GCE metadata "instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write" not defined
```

Am I doing something wrong or does bb-storage not support this connection method?

Storage Configuration:
```
{
  blobstore: {
    contentAddressableStorage: {
      cloud: {
        key_prefix: "cas",
        gcs: {
          bucket: "bazel-remote-execution-trusted.project-id.organisation-name",
        },
      },
    },
    actionCache: {
      cloud: {
        key_prefix: "ac",
        gcs: {
          bucket: "bazel-remote-execution-trusted.project-id.organisation-name",
        },
      },
    },
  },
  httpListenAddress: ':9980',
  grpcServers: [{
    listenAddresses: [':8981'],
    authenticationPolicy: { allow: {} },
  }],
  allowAcUpdatesForInstances: ['remote-execution'],
  maximumMessageSizeBytes: 16 * 1024 * 1024,
}
```

When switching to local storage, everything works correctly.

According to [instructions](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#enable_on_new_cluster), GCP service account successfully connected to pod:
```
I have no name!@storage-0:/$ gcloud auth list
                            Credentialed Accounts
ACTIVE  ACCOUNT
*       buildbarn-trusted-storage-service@project-id.iam.gserviceaccount.com
```

**Comment by mickael-carl** [comment]
Workload identity should be supported, we use the [FindDefaultCredentials](https://godoc.org/golang.org/x/oauth2/google#FindDefaultCredentials) method when credentials are not specified in the configuration. 
Just to rule out other issues, did you make sure that this service account has read/write access to the bucket you're using in IAM?

**Comment by GeniyX** [comment]
Yes, it seems that the error was in the incorrect username in one of the configuration files.
I recreated everything from scratch and the connection was successful.

Thanks for the tip =)
