### ISSUE TITLE
Exercise the JWT auth. caches expiry code

### ISSUE THREAD

**Issue by t-chaik** [buildbarn/bb-storage#7]
A slight downside is that we currently can't easily simulate cases where a token first becomes cached and then expires. If we wanted to do things a hundred percent tidy (and I'd leave it up to you whether you'd be up for that), we could remove all clock access from the Buildbarn codebase (is there any apart from the JWT handling?) by this:

https://github.com/benbjohnson/clock

We could let `auth.NewJWTAuthCache()` have a clock parameter.

But then the next problem becomes: jwt-go only has some very rudimentary code to override the clock. It can only be replaced globally, as opposed to per parser. Here's a local patch we could add/try to upstream.

[jwt-go.diff.gz](https://github.com/buildbarn/bb-storage/files/2972656/jwt-go.diff.gz)

Thoughts?

_Originally posted by @EdSchouten in https://github.com/buildbarn/bb-storage/pull/6_

**Comment by EdSchouten** [comment]
Closing this issue, as the corresponding PR has also been abandoned.
