### ISSUE TITLE
Unit test TestLocalDirectoryEnterSymlink fails on RHEL7, ELOOP returned instead of ENOTDIR

### ISSUE THREAD

**Issue by ehkloaj** [buildbarn/bb-storage#71]
The unit test [TestLocalDirectoryEnterSymlink](https://github.com/buildbarn/bb-storage/blob/master/pkg/filesystem/local_directory_test.go#L69-L75) fails on our Red Hat Enterprise Linux 7 system. 
The test checks if the error code ENOTDIR is returned but on our system ELOOP is returned instead.
https://github.com/buildbarn/bb-storage/blob/master/pkg/filesystem/local_directory_test.go#L73

When reading about the issue we have found that ELOOP should be returned when too many symbolic links were encountered in the resolving pathname or when O_NOFOLLOW was specified but pathname was a symbolic link (see [source](https://www.tutorialspoint.com/unix_system_calls/open.htm)).

When investigating the code we have found that [O_NOFOLLOW](https://www.gnu.org/software/findutils/manual/html_node/find_html/O_005fNOFOLLOW.html) is specified in the syscall and therefore we think that the correct behavior should be to return ELOOP not ENOTDIR since the test tries to open a symlink to the root folder ("/").
https://github.com/buildbarn/bb-storage/blob/master/pkg/filesystem/local_directory.go#L54

We are not sure if this is behavior is due to our specific environment or if it is to be seen as a bug in the test. For those of you who got this test to pass it would be really helpful if you could provide us with which OS you are running on.

**Comment by EdSchouten** [comment]
> For those of you who got this test to pass it would be really helpful if you could provide us with which OS you are running on.

The test currently passes on Ubuntu 18.04, macOS 10.15, and on Linux-based GitHub Actions workers (container image `docker://l.gcr.io/google/bazel:2.1.0`)

**Comment by ehkloaj** [comment]
Thank you for the fast response @EdSchouten.

Then it seems that it has something to do with our environment. I will keep looking.

**Comment by ehkloaj** [comment]
According to the [Linux Manual](https://man7.org/linux/man-pages/man2/open.2.html) ELOOP is returned when _pathname was a symbolic link, and flags specified O_NOFOLLOW but not O_PATH_. Specifying O_PATH solves the problem for us and does not break any other test.
`fd, err := unix.Openat(d.fd, name, unix.O_DIRECTORY|unix.O_NOFOLLOW|unix.O_RDONLY|unix.O_PATH, 0)`

We are not yet sure why it works without O_PATH on your system but not on ours but my guess is that it is because RHEL7 is using an older kernel (3.10.0-1127.8.2.el7.x86_64). What do you think @EdSchouten?

My colleague @ehrtro will post a PR with this solution shortly if we do not find anything new and then we will see if this had any affect on your systems.

**Comment by EdSchouten** [comment]
> We are not yet sure why it works without O_PATH on your system but not on ours but my guess is that it is because RHEL7 is using an older kernel (3.10.0-1127.8.2.el7.x86_64). What do you think @EdSchouten?

Yeah, it's likely just a bug in older versions of Linux. Let's continue discussing this in #72!
