### ISSUE TITLE
Implement GetTree

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-storage#95]
Following discussions over on https://github.com/bazelbuild/remote-apis/issues/165, it seems like the API has reason for using the Directory message over Tree. GetTree will provide a means for retrieving a tree from an API call. Whilst it would be relatively expensive to construct this tree on deep directory trees, caching these constructed Tree objects within the CAS should significantly reduce the required work for bb-storage.

I think the primary problem here is the additional maintenance burden on an additional API surface which currently only has one dependant (as far as I am aware).

**Comment by EdSchouten** [comment]
Considering that nothing really uses this, I'm not going to implement this. I hope that REv3 will also have no equivalent of this call.
